# CMake generated Testfile for 
# Source directory: /mnt/e/work/opendlms/openspodes
# Build directory: /mnt/e/work/opendlms/openspodes/build-bench
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(openspodes_test "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test")
set_tests_properties(openspodes_test PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;117;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_golden "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_golden")
set_tests_properties(openspodes_test_golden PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;122;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_errors "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_errors")
set_tests_properties(openspodes_test_errors PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;127;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_ic "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_ic")
set_tests_properties(openspodes_test_ic PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;132;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_integration "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_integration")
set_tests_properties(openspodes_test_integration PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;137;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_phase0 "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_phase0")
set_tests_properties(openspodes_test_phase0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;142;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_phase1 "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_phase1")
set_tests_properties(openspodes_test_phase1 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;151;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_phase2 "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_phase2")
set_tests_properties(openspodes_test_phase2 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;156;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_spodus "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_spodus")
set_tests_properties(openspodes_test_spodus PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;161;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_gost "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_gost")
set_tests_properties(openspodes_test_gost PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;166;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_hdlc "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_hdlc")
set_tests_properties(openspodes_test_hdlc PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;171;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_framing "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_framing")
set_tests_properties(openspodes_test_framing PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;176;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_security "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_security")
set_tests_properties(openspodes_test_security PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;184;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_loopback_cli_demo "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_loopback_cli" "demo")
set_tests_properties(openspodes_loopback_cli_demo PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;204;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_push_listener_demo "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_push_listener")
set_tests_properties(openspodes_push_listener_demo PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;213;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
add_test(openspodes_test_thread "/mnt/e/work/opendlms/openspodes/build-bench/openspodes_test_thread")
set_tests_properties(openspodes_test_thread PROPERTIES  _BACKTRACE_TRIPLES "/mnt/e/work/opendlms/openspodes/CMakeLists.txt;291;add_test;/mnt/e/work/opendlms/openspodes/CMakeLists.txt;0;")
subdirs("_deps/cmocka-build")
